#!/bin/bash

#add "build" folder, and then just run this simple script to build!  :)

clear && rm -rf ../build/* && cmake -G "Unix Makefiles" .. && echo . && echo PRESS ENTER && read -n 1 && clear && make clean && make
